#!/usr/bin/env bash

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mkdir -p "$HOME"/.config

###############################################################
# ZSH
###############################################################
# no typo I don't want to have a hidden file
# so it's not .zshrc
ln -sf "$DOTFILES"/zsh/zshrc "$HOME"/.zshrc

rm -rf "$HOME"/.config/zsh
ln -sf "$DOTFILES"/zsh "$HOME"/.config/zsh
ln -sf "$DOTFILES/tmux/tmux.conf" "$HOME/.tmux.conf"

rm -rf "$HOME"/.config/spaceship
ln -sf "$DOTFILES"/spaceship "$HOME"/.config/spaceship

###############################################################
# NPM
###############################################################
rm -rf "$HOME"/.npmrc
ln -sf "$DOTFILES"/npm/npmrc "$HOME"/.npmrc

###############################################################
# nvim
###############################################################
rm -rf "$HOME"/.config/nvim
ln -s "$DOTFILES"/nvim "$HOME"/.config/nvim

###############################################################
# alacritty
###############################################################
rm -rf "$HOME"/.config/alacritty
ln -s "$DOTFILES"/alacritty "$HOME"/.config/alacritty

###############################################################
# WezTerm
###############################################################
rm -rf "$HOME"/.wezterm.lua
ln -s "$DOTFILES"/WezTerm/ "$HOME"/.config/wezterm
# ln -s "$DOTFILES"/WezTerm/config.lua "$HOME"/.wezterm.lua

###############################################################
# zellij
###############################################################
rm -rf "$HOME"/.config/zellij
ln -s "$DOTFILES"/zellij "$HOME"/.config/zellij

###############################################################
# git
###############################################################
ln -sf "$DOTFILES"/git/gitconfig "$HOME"/.gitconfig
ln -sf "$DOTFILES"/git/gitignore_global "$HOME"/.gitignore_global

###############################################################
# phpactor
###############################################################
rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

if ! command -v npm &> /dev/null
then
    echo "npm executable could not be found"
else
    mkdir -p "${HOME}/.local/share/npm-packages"
    npm config set prefix "${HOME}/.local/share/npm-packages"

    npm i -g tree-sitter-cli intelephense
fi

if ! command -v git &> /dev/null
then
    echo "git executable could not be found"
else
    # nvim
    mkdir -p "${HOME}/.local/share/nvim/opt"
    git clone git@github.com:phpactor/phpactor "${HOME}/.local/share/nvim/opt/phpactor"
    # tmux
    git clone https://github.com/tmux-plugins/tpm "${HOME}/.config/tmux/plugins/tpm"
fi

if ! command -v composer &> /dev/null
then
    echo "git executable could not be found"
else
    mkdir -p "${HOME}/.local/share/composer"
    ln -sf "$DOTFILES"/composer/composer.json "$HOME"/.config/composer/composer.json
    composer global install
fi

if ! command -v cargo &> /dev/null
then
    echo "cargo executable could not be found"
else
    cargo install stylua
fi
