# This file should be sourced before activate zsh-syntax-highlighting
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)
typeset -gA ZSH_HIGHLIGHT_STYLES

# Main highlighter styling: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md

# General
ZSH_HIGHLIGHT_STYLES[alias]="fg=${colors[cyan]}"
ZSH_HIGHLIGHT_STYLES[arg0]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[assign]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[autodirectory]="fg=${colors[yellow]},italic"
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]="fg=${colors[red]}"
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]="fg=${colors[red]}"
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]="fg=${colors[red]}"
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]="fg=${colors[red]}"
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]="fg=${colors[purple]}"
ZSH_HIGHLIGHT_STYLES[builtin]="fg=${colors[cyan]}"
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]="fg=${colors[green]}"
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]="fg=${colors[green]}"
ZSH_HIGHLIGHT_STYLES[command]="fg=${colors[cyan]}"
ZSH_HIGHLIGHT_STYLES[commandseparator]="fg=${colors[red]}"
ZSH_HIGHLIGHT_STYLES[comment]="fg=${colors[dark2]}"
ZSH_HIGHLIGHT_STYLES[cursor]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[default]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]="fg=${colors[red]}"
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]="fg=${colors[yellow]}"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]="fg=${colors[red]}"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]="fg=${colors[green]}"
ZSH_HIGHLIGHT_STYLES[function]="fg=${colors[cyan]}"
ZSH_HIGHLIGHT_STYLES[global-alias]="fg=${colors[cyan]}"
ZSH_HIGHLIGHT_STYLES[globbing]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[hashed-command]="fg=${colors[cyan]}"
ZSH_HIGHLIGHT_STYLES[history-expansion]="fg=${colors[purple]}"
ZSH_HIGHLIGHT_STYLES[named-fd]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[numeric-fd]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[path]="fg=${colors[fg]},underline"
ZSH_HIGHLIGHT_STYLES[path_pathseparator]="fg=${colors[red]},underline"
ZSH_HIGHLIGHT_STYLES[path_prefix]="fg=${colors[fg]},underline"
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]="fg=${colors[red]},underline"
ZSH_HIGHLIGHT_STYLES[precommand]="fg=${colors[cyan]},italic"
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[rc-quote]="fg=${colors[green]}"
ZSH_HIGHLIGHT_STYLES[redirection]="fg=${colors[fg]}"
ZSH_HIGHLIGHT_STYLES[reserved-word]="fg=${colors[cyan]}"
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]="fg=${colors[yellow]}"
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]="fg=${colors[red]}"
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]="fg=${colors[green]}"
ZSH_HIGHLIGHT_STYLES[suffix-alias]="fg=${colors[cyan]}"
ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=${colors[red]}"
