#!/bin/sh
alias k="echo -e 'clear<CR>'"

alias dotfiles="nvim $HOME/dotfiles/$1"
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

alias luamake=/home/antoine/tmp/lua-language-server/3rd/luamake/luamake

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# replace git with config alias for dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# vim point to nvim
alias nvi="nvim"
alias c="nvim"
alias vi="nvim"
alias vim="nvim"

alias files="nautilus"
#
# LARAVEL
alias pamt="php artisan make:test"
alias pas="php artisan serve"
alias pat="php artisan tinker"
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
alias samt="./vendor/bin/sail artisan make:test"
alias sas="./vendor/bin/sail artisan serve"
alias sat="./vendor/bin/sail  artisan tinker"

# PHP UNIT
alias puc="XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-html"
alias pu="vendor/bin/phpunit --color"
alias puf="vendor/bin/phpunit --color --filter "

# COMPOSER
alias cda="composer dump-autoload"
alias cu="composer update"
alias bat="/usr/bin/batcat"

# YARN
alias yw="yarn watch"
alias yd="yarn dev"
alias yu="yarn upgrade"
alias ys="yarn serve"

# GIT
alias ga="git add"
alias gaa="git add ."
alias gs="git status"
alias nah="git reset --hard && git clean -df"

# create a directory if doesn't exist
# move into it
mkd () {
	mkdir -p "$@" && cd "$@";
}

function cdl () {
	cd "$@" && ls
}

function cd_up() {
	cd $(printf "%0.s../" $(seq 1 $1 ));
}

alias 'cd..'='cd_up'
