#!/bin/sh
alias k="echo -e 'CTRL+u'"

alias dotfiles="nvim $HOME/dotfiles/$1"
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"

alias mach_java_mode="export SDKMAN_DIR="$HOME/.sdkman" && [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh""

alias m="git checkout master"
alias s="git checkout stable"

alias luamake=/home/antoine/tmp/lua-language-server/3rd/luamake/luamake

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# replace git with config alias for dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# vim point to nvim
alias nvi="nvim"
alias c="nvim"
alias vi="nvim"
alias vim="nvim"

alias files="nautilus"
#
# LARAVEL
alias pamt="php artisan make:test"
alias pas="php artisan serve"
alias pat="php artisan tinker"
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'
alias samt="./vendor/bin/sail artisan make:test"
alias sas="./vendor/bin/sail artisan serve"
alias sat="./vendor/bin/sail  artisan tinker"

# PHP UNIT
alias puc="XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-html"
alias pu="vendor/bin/phpunit --color"
alias puf="vendor/bin/phpunit --color --filter "

# COMPOSER
alias cda="composer dump-autoload"
alias cu="composer update"
alias bat="/usr/bin/batcat"

# YARN
alias yw="yarn watch"
alias yd="yarn dev"
alias yu="yarn upgrade"
alias ys="yarn serve"

# GIT
alias ga="git add"
alias gaa="git add ."
alias gs="git status"
alias nah="git reset --hard && git clean -df"

# create a directory if doesn't exist
# move into it
mkd () {
	mkdir -p "$@" && cd "$@";
}

function cdl () {
	cd "$@" && ls
}

function cd_up() {
	cd $(printf "%0.s../" $(seq 1 $1 ));
}

alias 'cd..'='cd_up'
