#!/bin/sh

export MANPAGER='nvim +Man!'
export MANWIDTH=999

# add rust cargo to path
PATH=$PATH:"$HOME/.cargo/bin"

# add user's bin to path
# export PATH="$HOME/.local/bin":$PATH
if command -v node &> /dev/null; then
    PATH=$PATH:"$HOME/.local/bin"
    PATH=$PATH:"$HOME/node_modules/.bin"
fi

# Per user npm bin
if command -v npm &> /dev/null; then
    NPM_PACKAGES="${HOME}/.local/share/npm-packages"
    PATH="$PATH:$NPM_PACKAGES/bin"
    # Preserve MANPATH if you already defined it somewhere in your config.
    # Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
    export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"
fi

# Per user composer bin
if command -v composer &> /dev/null; then
    PATH="$(composer config -g home)/.local/share/composer/vendor/bin:$PATH"
fi

# Per user add mason bin to path 
MASON_PACKAGES="${HOME}/.local/share/nvim/mason"
PATH="$PATH:$MASON_PACKAGES/bin"

# Per user go 
PATH=$PATH:/usr/local/go/bin
GOPATH=$HOME/.local/share/go

# Per user lua 
LUA_PACKAGES="${HOME}/.luarocks/"
PATH="$PATH:$LUA_PACKAGES/bin"

TMP_HOME_PATH="${HOME}/tmp/"
# Yazi
PATH="$PATH:$TMP_HOME_PATH/yazi/target/release/"
# Wezterm
PATH="$PATH:$TMP_HOME_PATH/wezterm/target/release/"

export PATH
