export ZSH=$HOME/.oh-my-zsh
source ~/.config/zsh/zsh-aliases
source ~/.config/zsh/zsh-exports
# source ~/.config/zsh/zsh-path

ZSH_THEME="spaceship"
HIST_STAMPS="dd/mm/yyyy"

plugins=(
    composer
    debian
    git
    git
    laravel
    npm
)

export COLORTERM=truecolor
export LC_ALL=en_US.UTF-8
#
# Per user npm bin
NPM_PACKAGES="${HOME}/.local/share/npm-packages"
PATH="$PATH:$NPM_PACKAGES/bin"

# Per user composer bin
PATH="$(composer config -g home)/.local/share/composer/vendor/bin:$PATH"
# Preserve MANPATH if you already defined it somewhere in your config.
# Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"

# Per user go 
PATH=$PATH:/usr/local/go/bin

# Per user lua 
LUA_PACKAGES="${HOME}/.luarocks/"
PATH="$PATH:$LUA_PACKAGES/bin"

export PATH
source $ZSH/oh-my-zsh.sh

export OPENAI_API_KEY=`pass show chatgpt`
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# bun completions
[ -s "/home/antoine/.bun/_bun" ] && source "/home/antoine/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
